server {
  listen ${PORT} default_server;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # SPA routing
  location / {
    try_files $uri $uri/ /index.html;
  }

  location = /assets/config.json {
    add_header Cache-Control "no-store";
    try_files $uri =404;
  }

  gzip on;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
}
