server.port=8080
spring.application.name=expense-tracker-api

spring.datasource.url=jdbc:h2:file:./data/expenses;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.jwt.secret=ExpenseTrackerSecretKeyChangeMeInProduction_2026_SecureLongValue
app.jwt.expiration-ms=2592000000
